### PR TITLE
Add-TMT-proteomics-template

### PR DESCRIPTION
**Pull request by ameliakallaher**
Created a new TMT proteomics template, updated the UsedIn for some attributes, and created new attributes for this metadata template.

### CODE REVIEW

**Comment by avanlinden** [comment]
[el_assay_tmt_proteomics_template.xlsx](https://github.com/user-attachments/files/16461525/el_assay_tmt_proteomics_template.xlsx)
@ameliakallaher here's the ELITE proteomics template generated via schematic CLI

**Comment by ameliakallaher** [comment]
To do: open a Bug with FAIR Data for 'replicate' attribute not appearing as it should.
21A3A881-A384-43F3-951B-AF566D529B90

**Comment by ameliakallaher** [comment]
[TMT proteomicss assay template](https://docs.google.com/spreadsheets/d/1FX_c4sEoVrjkI8kXp1wYiM1U0hBG1Ft0tDtfYVcU7ik/edit?gid=0#gid=0)

Note: removed tissue manually before sending to contributor.

**Comment by avanlinden** [comment]
To try out the new automation, I'm going to close this PR and open a new one on the same branch.

**Pull request closed without merging**
