### PR TITLE
Update-bsSeq-enums

### PR DESCRIPTION
**Pull request by ameliakallaher**
Updated enumerated values lists with options for unknown, not collected, not specified, and not applicable.

### CODE REVIEW

**Comment by avanlinden** [comment]
GH action is expected to fail. Running `join_data_model.py` script did not update the json-ld because changes are to columns that are ignored by schematic (e.g. columnType).

**Review by avanlinden — APPROVED** [review]

**Comment by ameliakallaher** [comment]
@avanlinden The template didn't update in DCA with these changes - I ran the Python line above as one of my commits, but perhaps not successfully?

**Comment by avanlinden** [comment]
The `join_data_model.py` script silently failed because we did not have schematic installed in the environment! Updated process to manually do this:

1. run `poetry install` in the terminal
2. run `poetry shell` in the terminal
3. then run `data_model_creation/join_data_model.py`
4. check to see that both data model csv and json-ld files get updated!

**Comment by avanlinden** [comment]
something weird happening with the `totalReads.csv` attribute, line 147 in the csv data model, preventing schematic from converting to jsonld

**Pull request merged**
